# Generated by Django 6.1 on 2026-08-28 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=200, verbose_name='title')),
                ('district', models.CharField(max_length=100, verbose_name='district')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('price', models.IntegerField(verbose_name='price ($)')),
                ('rooms', models.CharField(max_length=10, verbose_name='rooms')),
                ('meters', models.FloatField(verbose_name='area (m²)')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('images', models.JSONField(default=list, verbose_name='photos')),
                ('floor', models.CharField(max_length=30, verbose_name='floor')),
                ('seller_name', models.CharField(blank=True, max_length=100, verbose_name='seller name')),
                ('phone', models.CharField(blank=True, max_length=70, verbose_name='phone')),
                ('link', models.URLField(blank=True, verbose_name='link')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'announcement')},
            },
        ),
    ]
